# Generated by Django 4.0.6 on 2022-08-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trailers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailers',
            name='cast',
            field=models.TextField(default='d', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailers',
            name='description',
            field=models.TextField(default='s', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailers',
            name='image',
            field=models.ImageField(default='s', upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailers',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='trailers',
            name='title',
            field=models.TextField(default='d', max_length=70, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailers',
            name='trailerUrl',
            field=models.TextField(default='w', max_length=15),
            preserve_default=False,
        ),
    ]
