# Generated by Django 4.0.6 on 2022-08-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trailers', '0003_remove_trailers_category_trailers_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailers',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
